=== nandha005/Python/user_data.xsd
<?xml version="1.0" ?>
<xs:schema xmlns:xs = "http://www.w3.org/2001/XMLSchema">
<xs:element name="Hcsc">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="Insurer" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="Name">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="FirstName" type="xs:string">

                                    </xs:element>
                                    <xs:element name="LastName" type="xs:string">

                                    </xs:element>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                        <xs:element name="Premium" type="xs:string">

                        </xs:element>
                        <xs:element name="Age" type="xs:int">

                        </xs:element>
                        <xs:element name="Address">
                             <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="Town" type="xs:string">

                                    </xs:element>
                                    <xs:element name="Country" type="xs:string">

                                    </xs:element>
                                    <xs:element name="Pincode" type="xs:string">

                                    </xs:element>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                        <xs:element name="PolicyNumber" type="xs:string">

                        </xs:element>
                    </xs:sequence>
                    <xs:attribute name="Policyid" type="xs:int" use="required">

                    </xs:attribute>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:element>
</xs:schema>

=== nandha005/Python/user_data.xml
<?xml version="1.0" ?>
<Hcsc xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="user_data.xsd">
    <Insurer Policyid="123">
        <Name>
            <FirstName>Nandha</FirstName>
            <LastName>Kumar</LastName>
        </Name>
        <Premium>5000</Premium>
        <Age>22</Age>
        <Address>
            <Town>Udumalpet</Town>
            <Country>India</Country>
            <Pincode>626641</Pincode>
        </Address>
        <PolicyNumber>1234</PolicyNumber>

    </Insurer>
    <Insurer Policyid="124">
        <Name>
            <FirstName>Prasanna</FirstName>
            <LastName>Prakasam</LastName>
        </Name>
        <Premium>8000</Premium>
        <Age>20</Age>
        <Address>
            <Town>Udumalpet</Town>
            <Country>India</Country>
            <Pincode>626641</Pincode>
        </Address>
        <PolicyNumber>1231</PolicyNumber>
    </Insurer>
    <Insurer Policyid="125">
         <Name>
            <FirstName>Priya</FirstName>
            <LastName>Dharshini</LastName>
        </Name>
        <Premium>21000</Premium>
        <Age>26</Age>
        <Address>
            <Town>Udumalpet</Town>
            <Country>India</Country>
            <Pincode>626641</Pincode>
        </Address>
        <PolicyNumber>1232</PolicyNumber>
    </Insurer>
    <Insurer Policyid="126">
        <Name>
            <FirstName>guru</FirstName>
            <LastName>lakshmi</LastName>
        </Name>
        <Premium>7000</Premium>
        <Age>24</Age>
        <Address>
            <Town>Udumalpet</Town>
            <Country>India</Country>
            <Pincode>626641</Pincode>
        </Address>
        <PolicyNumber>1235</PolicyNumber>
    </Insurer>
    <Insurer Policyid="127">
        <Name>
            <FirstName>Moni</FirstName>
            <LastName>sha</LastName>
        </Name>
        <Premium>5500</Premium>
        <Age>27</Age>
        <Address>
            <Town>Udumalpet</Town>
            <Country>India</Country>
            <Pincode>626641</Pincode>
        </Address>
        <PolicyNumber>1236</PolicyNumber>
    </Insurer>
    <Insurer Policyid="128">
         <Name>
            <FirstName>Nandha</FirstName>
            <LastName>Kumar</LastName>
        </Name>
        <Premium>7050</Premium>
        <Age>28</Age>
        <Address>
            <Town>Udumalpet</Town>
            <Country>India</Country>
            <Pincode>626641</Pincode>
        </Address>
        <PolicyNumber>1237</PolicyNumber>
    </Insurer>
</Hcsc>
